spring:
  main:
    lazy-initialization: true
  dataSource:
    url: jdbc:postgresql://127.0.0.1:5432/person
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    generate_statistics: true
  jpa:
    # show SQL statements in console.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

server:
  port: 8080
  servlet:
    context-path: "/api"
  error:
    include-message: always

logging:
  level:
    root: info
  file:
    name: log/app.log


